### ISSUE TITLE
Not found: reference/mutation_type_dictionary.v4.txt

### ISSUE THREAD

**Issue by ulloaa** [getzlab/MutSig2CV#25]
Hello, 

We have downloaded hg38 reference files from: 

[gs://getzlab-mutsig2cv-reference-files/hg38](url)

and have followed instructions shown in:

[https://github.com/getzlab/MutSig2CV/issues/10](url)

However, we still get the error:

`Not found: reference/mutation_type_dictionary.v4.txt
`
Could you please advise?

Thank you!

**Comment by julianhess** [comment]
Hi,

The mutation type dictionary is the same between hg19 and hg38. Please use the file from the hg19 bundle.

—Julian

**Comment by ulloaa** [comment]
thanks so much for your prompt response; what about the other required files that are not included in the hg38 reference?

 such as:
`
'reference/mutation_type_dictionary.v4.txt'
'reference/coverage_models.v5a.mat'
'reference/coverage_basewise.fwb'
'reference/target_list.hg19.v1a.txt'
'reference/context_and_effect.c65e29b.fwb'
'reference/context_and_effect.c65e29b.txt'
'reference/covariates_transformed.v5a.txt'
'reference/conservation46.fwb'
'reference/FixedWidthBinary.jar'
`

Thanks again!

**Comment by julianhess** [comment]
Some of the files have been renamed between hg19 and hg38. Following the instructions in [this post](https://github.com/getzlab/MutSig2CV/issues/10#issuecomment-1142375852) should give you everything you need.

**Comment by sabertadros** [comment]
Hi,
We ran standalone version following exactly the steps as illustrated in the homepage.

`bin/MutSig2CV <path to mutations> <path to output directory> [params file]`

The parameter file we used are adapted from issue 10, as followed:

```
skip_permutations true
mutation_type_dictionary_file reference/mutation_type_dictionary.v4.txt
coverage_models_mat_file       reference/coverage_models.agilent.mat
target_list_file        reference/target_list.gencode25.txt
context_and_effect_fwb_file     reference/context_and_effect_track.fwb
context_and_effect_fwi_file     reference/context_and_effect_track.fwi
context_and_effect_categs_file  reference/context_and_effect_dict.txt
covariates_file        reference/covariates.agilent.txt
```

We used hg38 files from GCP, for the rest necessary files we used those from hg19 as you instructed above. And when we ran the program, the error messages are shown as following:

```
2CV v3.11
Warning: "FixedWidthBinary.jar" is already specified on static java path.
> In javaclasspath>local_validate_dynamic_path at 293
  In javaclasspath>local_javapath at 182
  In javaclasspath at 102
  In MutSig_2CV_v3_11_core at 27
  In MutSig_2CV_v3_11_wrapper at 51 
LOADING DATA
Error using MutSig_2CV_v3_11_core (line 90)
Java exception occurred: 
java.lang.Exception: File and index are mismatched, no matter what width is tried
at org.broadinstitute.cga.tools.seq.FixedWidthBinary.open(FixedWidthBinary.java:170)
at org.broadinstitute.cga.tools.seq.FixedWidthBinary.open(FixedWidthBinary.java:148)
at org.broadinstitute.cga.tools.seq.FixedWidthBinary.open(FixedWidthBinary.java:144)
at org.broadinstitute.cga.tools.seq.FixedWidthBinary.<init>(FixedWidthBinary.java:113)

Error in MutSig_2CV_v3_11_wrapper (line 51)
```

We wonder if the error might be related to the rest of the reference files including:
```
conservation46.fwb 
context_and_effect_track.fwi 
coverage_basewise.fwb
coverage_basewise.fwi        
mutation_type_dictionary.v4.txt
conservation46.fwi 
```       
What do you recommend? Thanks

**Comment by julianhess** [comment]
Hi,

This is coming from an issue with coverage_basewise.fwb/coverage_basewise.fwi. Is it possible that these files are not being specified properly (or corrupted)?

—Julian

**Comment by sabertadros** [comment]
Thanks for your response.
We ran the program specifying these two files in the params.txt and it returned with the same exact errors as in the previous post. Next, we ran the program with hg19 built using the same files and they worked fine. So, it seems that neither path specification nor file corruption is the cause for the error. 

```
skip_permutations true
mutation_type_dictionary_file reference/mutation_type_dictionary.v4.txt
coverage_models_mat_file       reference/coverage_models.agilent.mat
target_list_file        reference/target_list.gencode25.txt
context_and_effect_fwb_file     reference/context_and_effect_track.fwb
context_and_effect_fwi_file     reference/context_and_effect_track.fwi
context_and_effect_categs_file  reference/context_and_effect_dict.txt
basewise_coverage_fwb_file  reference/coverage_basewise.fwb
basewise_coverage_fwi_file  reference/coverage_basewise.fwi
covariates_file        reference/covariates.agilent.txt
```

Since we are using these 6 files from the hg19 built and comparable files for hg38 built are not included in the cloud link [as per issue 10], we believe that compatible reference files (coverage_basewise.fwb/coverage_basewise.fwi) for built hg38 if they are available might fix the problem.

What do you recommend?

**Comment by sunyl312** [comment]
> coverage_basewise

I encounter the same problem. it worked well while using the hg19, but encounter errors in hg38. Have you solved the problem? how can you solve it? Thank you very much.

**Comment by sabertadros** [comment]
Hi Julian,

I spent so long trying to troubleshoot the problem, and eventually, I had
to realign the data to hg19 to get it working.

I would love to hear your thoughts. Thanks

Best,
Saber

**Comment by lance8403** [comment]
Hi Saber,

You can download the whole folder:
$gsutil -m cp -r gs://getzlab-mutsig2cv-reference-files/ path/to/destination

You will see there're separated folders for hg19 and hg38, rename the folder to reference, and create the params.txt as below:

skip_permutations       True
mutation_type_dictionary_file reference/mutation_type_dictionary.v4.txt
coverage_models_mat_file        reference/hg38/coverage_models.agilent.mat
target_list_file        reference/hg38/target_list.gencode25.txt
context_and_effect_fwb_file     reference/hg38/context_and_effect_track.fwb
context_and_effect_fwi_file     reference/hg38/context_and_effect_track.fwi
context_and_effect_categs_file  reference/context_and_effect_dict.txt
covariates_file reference/hg38/covariates.agilent.txt

You may still get some warnings, but the results in the final output folder are all correct in my case.

Best,

Lance
